import sqlite3
import random
from datetime import datetime
import os

DB_PATH = os.path.join(os.path.dirname(__file__), 'yiyu.db')

def generate_mock_articles():
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()
    
    # Clear old data so we only see bilingual mock data
    c.execute('DELETE FROM articles')
    
    topics = [
        'TikTok 短视频广告出海投放策略与ROI提升', 
        'Google Ads 搜索广告账户防封技巧与申诉', 
        'Meta (Facebook) 广告高转化素材设计指南', 
        '海外游戏发行的买量成本(CAC)深度分析', 
        '出海电商独立站引流最新玩法与转化优化', 
        '企业级海外资金管理系统如何解决汇损问题'
    ]
    
    en_topics = [
        'TikTok Short Video Ad Strategies & ROI Boost for Global Expansion',
        'Google Ads Account Anti-ban Tips & Appeal Guide',
        'Meta (Facebook) High-Conversion Creative Design Guide',
        'In-depth Analysis of User Acquisition Costs (CAC) in Global Game Publishing',
        'Latest Traffic Acquisition Tactics & Conversion Optimization for Global E-commerce',
        'How Enterprise Global Fund Management Systems Solve FX Loss Issues'
    ]
    
    for i, topic in enumerate(topics):
        seed = random.randint(100, 9999)
        date_str = datetime.now().strftime('%Y-%m-%d')
        c.execute('''
            INSERT INTO articles (category_id, title, summary, content, date, views, image, seo_keywords, title_en, summary_en, content_en)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        ''', (
            random.choice(['news', 'insight', 'guide', 'update']),
            topic,
            f'这是关于【{topic}】的自动生成测试摘要。',
            f'## 1. 核心观点\n这是关于【{topic}】的自动生成测试正文。后续配置好 API Key 后，这里将被大模型生成的优质双语 Markdown 内容替换。\n\n## 2. 深度分析\n这里是深度干货内容。',
            date_str,
            random.randint(10, 100),
            f'https://picsum.photos/seed/yiyu{seed}/800/500',
            '出海, 广告, 投放',
            en_topics[i],
            f'This is an auto-generated mock summary for [{en_topics[i]}].',
            f'## 1. Core Insight\nThis is the English mock content for [{en_topics[i]}]. After setting up the API Key, this will be replaced with high-quality bilingual Markdown content generated by the AI model.\n\n## 2. Deep Analysis\nHere is the deep insight content.',
        ))
        
    conn.commit()
    conn.close()
    print('成功插入 6 篇测试文章！')

if __name__ == '__main__':
    generate_mock_articles()